### ISSUE TITLE
update default_prior function with new syntax

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#156]
in #152 i changed all other functions but I forgot to change get_model_prior(), which now because of that returns just the default brms priors. The generated stancode and fit_model use the correct prior, it's just wrong information when asking for it.

Which makes me realize that we don't have a test for whether the default priors are correct, so I'll add that too

Tasks:
- [x] Fix default_prior()
- [ ] Write tests for default priors of all models - moved to #159 
- [ ] Write tests for stancode - moved to #159 
- [ ] Disable sort_data check for stancode and default_prior - moved to #158

**Comment by venpopov** [comment]
Also noticed hat the sort_data check happens when calling default_prior as well, but it shouldn't. It also shouldn't happen with stancode. Will fix both here as well.
